USE first_db;

CREATE TABLE Department(id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY, 
    name VARCHAR(30) NOT NULL);

CREATE TABLE Employees(id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY, 
    name VARCHAR(30) NOT NULL,
    department_id INT(6) NOT NULL);

INSERT INTO Department (name) VALUES ("Fire");

SELECT * FROM Department; 